# Generated by Django 4.2.20 on 2025-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
