# Generated by Django 4.2.20 on 2025-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_player_latitude_player_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='district',
            field=models.BooleanField(default=False),
        ),
    ]
